language: php

php:
  - "7.2"

install:
  - ./scripts/composer.sh install --no-interaction

script:
  - ./scripts/print-info.sh
  - ./scripts/prepare-build.sh
  - ./scripts/phpunit.sh --coverage-clover ./build/logs/clover.xml

after_success:
  - travis_retry ./scripts/coveralls.sh
